import { walkthroughActions } from "./walkthroughActions.js";
// Keep these instructions tied to visible controls. No tutorial step edits analysis data.
export const createWalkthroughSteps = (sessionCount) => {
  const step = (workflow, id, title, description, target, extra = {}) => ({ workflow, id, title, description, target, action: walkthroughActions[id], ...extra });
  const overview = { workspace: "overview", prerequisite: "Create or select a session. This control is in Instrument Overview." };
  const budget = { workspace: "budget", prerequisite: "Create a measurement point, select its row, and open Uncertainty Budget." };
  const derived = { ...budget, prerequisite: "Choose Derived in Measurement Area Settings, create a new point, and select that point in Uncertainty Budget." };
  const points = '.measurement-point-list';
  const tmde = '[data-tour="tmde-table"]';
  const uut = '[data-tour="uut-table"]';
  const addBudget = '[data-tour="budget-add-component"]';
  const budgetMenu = '[data-tour="budget-component-menu"]';
  const columns = '[data-tour="sidebar-columns"]';
  const settings = '[data-tour="function-settings"]';
  const settingsMenu = '[data-tour="function-settings-menu"]';
  const steps = [
    step("Session setup", "new-session", "Start an analysis session",
      "Use + to create a session for your instruments, measurement points, budgets, requirements, and notes. Complete the highlighted action to advance after a green pulse. Use Skip, Workflow, or Jump to step to move ahead, and close the tutorial at any time.",
      '[data-tour="add-session"]', { canAdvance: sessionCount > 0,
        hint: sessionCount ? "Continue with the current session or create another. Tutorial actions use your real session; changes save as you edit." : "Click + to begin. You can close Help and reopen it at any time." }),
    step("Session setup", "session-information", "Complete the session information",
      "Expand Session Info to name the analysis and enter the analyst, organization, document, and date. These details identify the analysis when you return to it or export it.",
      '[data-tour="session-information"]', { hint: "Switch between saved analyses using the session selector. Fields save as you edit." }),
    step("Session setup", "session-requirements", "Set the starting risk and mitigation inputs",
      "Expand Risk & Mitigation Inputs. Set confidence, assumed end-of-period reliability (REOP), TUR needed, PFA required, REOP required, and the current calibration interval. These are the defaults for points in this session.",
      '[data-tour="session-requirements"]', { hint: "Hover each label for its definition. Point-specific overrides are available through the measurement-point columns." }),

    step("Instruments & Measurement Areas", "overview-tab", "Open Instrument Overview",
      "The UUT table defines units under test and their tolerances. The TMDE table defines measuring equipment and its uncertainties. Build your session's instrument definitions here; each measurement point then chooses its own budget sources.",
      '[data-tour="tab-overview"]', overview),
    step("Instruments & Measurement Areas", "uut-function", "Create a Measurement Area",
      "Type a name in Add Measurement Area and press Enter or +. You can do this from Measurement Points or either instrument table. New areas receive a random color; use the color dot to choose your own and click the area name to rename it.",
      '[data-tour="uut-add-function"]', { ...overview, hint: "Areas organize work, not instrument compatibility. An area can contain instruments with different functions and units." }),
    step("Instruments & Measurement Areas", "uut-instrument", "Add the unit under test",
      "Use + on the UUT area's header. Click Description to search the library by manufacturer, model, name, or function, then choose a result explicitly. You can also enter a new instrument definition.",
      '[data-tour="uut-add-instrument"]', { ...overview, hint: "Use a tag or nickname to distinguish similar instruments. The empty-table arrow points to the add control." }),
    step("Instruments & Measurement Areas", "uut-columns", "Define ranges and specifications",
      "Click a Range cell to enter its limits or single value and unit. Use its + to add another range. Click Tolerance or Resolution to edit the specification. Choose symmetric ± or asymmetric +/− limits and double-sided (DS) or single-sided (SS) behavior as appropriate.",
      uut, { ...overview, hint: "Percent of indicated value (IV), percent of full scale (FS), absolute-unit, and dB terms describe different specifications. For % FS, enter the applicable full-scale value." }),
    step("Instruments & Measurement Areas", "instrument-units", "Choose units, prefixes, and distributions",
      "Use the searchable unit menu and the separate prefix menu in inline editors. A prefix changes the displayed scale. TMDE Distribution converts an error limit into standard uncertainty; resolution has its own distribution setting.",
      uut, { ...overview, revealedTarget: ".inline-unit-menu", hint: "Units is the unset unit choice. Not Set means a field has not been configured; it does not establish a zero uncertainty." }),
    step("Instruments & Measurement Areas", "tmde-function", "Add measuring equipment",
      "The Measurement Area you created in the UUT table already appears in the TMDE table. Use + on that same area header to add equipment. Search Description or enter a definition, then fill in Range, Uncertainty, Distribution, and Resolution.",
      '[data-tour="tmde-add-instrument"]', { ...overview, prerequisite: "Create a Measurement Area once; it is shared by the point list, UUT table, and TMDE table.", hint: "Adding equipment here makes its sources available; it does not automatically put every source into every budget." }),
    step("Instruments & Measurement Areas", "area-tools", "Select instruments or individual ranges",
      "Click a Range cell to select that range. Clicking another column also highlights the instrument's shared Description and other shared cells. Ctrl/Cmd-click adds selections; Shift-click selects a span. Selected rows reveal their delete controls on hover.",
      tmde, { ...overview, hint: "Right-click for the available actions. Drag instruments between areas to associate them with another area." }),
    step("Instruments & Measurement Areas", "custom-columns", "Add custom instrument information",
      "Use the small + above a column divider to insert a custom column. Rename the heading and fill in its cells. Drag header dividers to resize columns; double-click a divider to reset its width.",
      uut, { ...overview, revealedTarget: '[data-tour="uut-table"] .instrument-column-insert-button, .inline-unit-menu', hint: "Custom columns store your supporting information alongside the instrument specifications." }),

    step("Additional uncertainties", "instrument-sources", "Add a named uncertainty to an instrument",
      "Expand a TMDE Uncertainty cell and use + at its top right. A new row appears under ADD’L UNCERTAINTY. Click Not Set in the Range column to name it, then edit its Uncertainty value and set its distribution in the adjacent Distribution column. The + remains available from every expanded uncertainty editor.",
      tmde, { ...overview, revealedTarget: '.instrument-source-toolbar', hint: "Examples include temperature effects or alignment error. Each named source can be selected separately for a budget." }),
    step("Additional uncertainties", "source-types", "Choose Manual, Table, or Equation",
      "In an expanded uncertainty editor, use the gear to select Manual, Table, or Equation. Manual accepts specification terms; Table supplies uncertainty at matching points; Equation computes it from a formula. Choose the distribution in the adjacent Distribution column.",
      tmde, { ...overview, revealedTarget: '.instrument-source-settings', hint: "Changing type retains the distribution already selected. The type menu changes the source's input method, not its Type A/B classification." }),
    step("Additional uncertainties", "source-table", "Enter a tabular uncertainty",
      "A tabular uncertainty is a lookup table: each measurement value has its own uncertainty limit, such as values from a calibration certificate. Choose Table and set the uncertainty unit and prefix. Enter measurement points and their uncertainty values, using + Row for more entries. Use +/− when the limits are asymmetric. The selected point must have a matching table entry. Press Enter or Escape to collapse the editor when finished.",
      tmde, { ...overview, revealedTarget: '[aria-label="Tabular uncertainty editor"]', hint: "A missing match leaves the budget unresolved; inspect its warning. Do not assume values are interpolated between rows." }),
    step("Additional uncertainties", "source-equation", "Enter an uncertainty equation",
      "An equation uncertainty calculates an error limit that varies with the measurement value, such as a percentage term plus a fixed floor. First select a measurement point with a numeric Value and unit. Choose Equation, set the uncertainty unit, and enter a formula such as a * x + b. Name the variables and enter fixed values. Use a variable's link button to bind it to the measurement point instead of a fixed value. Press Enter or Escape to collapse the editor when finished.",
      tmde, { ...budget, revealedTarget: '[aria-label="Equation uncertainty editor"], .inline-unit-menu', hint: "This formula calculates one source's uncertainty. A derived measurement equation calculates the measurement result itself." }),
    step("Additional uncertainties", "source-distribution", "Set the additional source distribution",
      "Click Distribution on the additional uncertainty row and choose the distribution supported by that source. It converts the entered limit into standard uncertainty. Use the adjacent column for Manual, Table, and Equation sources; changing the source type retains this choice.",
      '[data-tour="tmde-table"] .instrument-uncertainty-row .cell-distribution', { ...overview, revealedTarget: '.inline-unit-menu' }),
    step("Additional uncertainties", "source-selection", "Select, delete, and budget individual sources",
      "Select the source's name cell to highlight just its row to the right of ADD’L UNCERTAINTY. Click another column to include the shared instrument cells and label strip. The row's × appears on hover after selection. In a budget, choose each source separately under its instrument.",
      tmde, { ...overview, hint: "The budget picker lists ordinary ranges as Range | Uncertainty | Distribution, and additional sources as Name (Type) | Uncertainty | Distribution." }),
    step("Additional uncertainties", "range-bias", "Record known bias at its source",
      "Find an ordinary instrument range row—the row with range limits, above ADD’L UNCERTAINTY. Click its UUT Tolerance or TMDE Uncertainty value, then enable Bias at the top of that editor. Additional Manual/Table/Equation rows do not have a Bias button. Enter the signed value and its unit or percentage basis. Bias shifts the error model; it is distinct from the uncertainty describing its spread.",
      '[data-tour="tmde-table"] tr[data-range-id]:not([data-uncertainty-source-id]) .cell-tolerance', { ...overview, revealedTarget: '.instrument-bias-editor', hint: "Check the sign and basis carefully. Review the risk breakdown after changing bias; do not count the same effect again as another source." }),

    step("Direct measurement", "function-settings", "Choose the direct workflow",
      "Hover a Measurement Area header in the point list and open its gear. Choose Direct for new points. Reuse the first point's budget lets subsequent points start with that area's first budget.",
      settings, { revealedTarget: settingsMenu, prerequisite: "Create a Measurement Area first so its header and settings are available.", hint: "These choices configure newly created points. Review copied sources at each new nominal." }),
    step("Direct measurement", "measurement-point", "Create a direct measurement point",
      "Use + on the Measurement Area header to create a new direct measurement point.",
      '[data-tour="add-measurement-point"]'),
    step("Direct measurement", "point-uut", "Assign the point's UUT",
      "Click the highlighted UUT cell and choose the instrument to test. Assignment opens this point's Uncertainty Budget automatically and supplies the UUT's default unit.",
      '.point-grid-item.active-point [data-sidebar-column="uut"]', { revealedTarget: '.inline-unit-menu', prerequisite: "Create or select a measurement point first." }),
    step("Direct measurement", "point-value", "Enter the measurement value",
      "Enter the nominal in the highlighted Value field, then press Enter. For a voltage example, use 5 V. You can change the default unit or prefix with its menus.",
      '.point-grid-item.active-point [data-sidebar-column="value"]', { revealedTarget: '.inline-unit-menu' }),
    step("Direct measurement", "budget-tab", "Review the opened Uncertainty Budget",
      "Assigning the UUT opened this budget automatically. Confirm the nominal, UUT range, and tolerance. Later, selecting another point opens its budget. The budget contains only the contributors selected for that point.",
      '.budget-stack', budget),
    step("Direct measurement", "budget-component", "Build the direct budget",
      "Use + in the budget header. Under each TMDE, choose the appropriate range or named uncertainty; add resolution when applicable. You can also add a manual, tabular, equation, or repeatability component. Check the range and units against this point's nominal.",
      addBudget, { ...budget, revealedTarget: budgetMenu, hint: "Each source should represent a distinct effect. A source listed in the instrument table is not included until you add it here." }),

    step("Derived measurement", "derived-settings", "Choose the derived workflow",
      "Open Measurement Area Settings and choose Derived before adding a point. Reuse the first point's equation copies its equation and variables; Reuse the first point's budget copies its contributors into new points.",
      settings, { revealedTarget: settingsMenu, prerequisite: "Create a Measurement Area first.", hint: "Use Derived when the result comes from multiple inputs, such as power from voltage and current." }),
    step("Derived measurement", "derived-point", "Create the derived target",
      "Use the area's + to create a derived measurement point. Its target describes the output of your measurement equation.",
      '[data-tour="add-measurement-point"]'),
    step("Derived measurement", "derived-uut", "Assign the output UUT",
      "Choose the output instrument from the highlighted UUT cell. Its budget opens automatically. For power, choose the UUT measuring the power output.",
      '.point-grid-item.active-point [data-sidebar-column="uut"]', { revealedTarget: '.inline-unit-menu', prerequisite: "Create or select a derived measurement point first." }),
    step("Derived measurement", "derived-value", "Enter the output target",
      "Enter the output target and unit in Value, then press Enter. For example, the target might be 10 W while the equation inputs are 5 V and 2 A.",
      '.point-grid-item.active-point [data-sidebar-column="value"]', { revealedTarget: '.inline-unit-menu' }),
    step("Derived measurement", "derived-equation", "Enter the measurement equation",
      "Click the measurement equation preview and enter x * y for the power example. Use f(x) to insert a function or symbol, or Library for a common metrology equation. Press Enter to finish editing.",
      '.measurement-equation-card', { ...derived, hint: "This is the relationship between the measured output and its inputs, not an uncertainty equation for a single source." }),
    step("Derived measurement", "derived-nominals", "Set every input nominal",
      "Name the inputs, then enter their values and units: x = 5 V and y = 2 A produce 10 W. Input nominals are independent of the instruments you add later. Review warnings if a unit is incompatible or the calculated result differs from the target.",
      '.measurement-inputs-table-wrap', derived),
    step("Derived measurement", "derived-sources", "Build each input budget",
      "Use + on each input budget: voltage sources belong to x and current sources to y in this example. Any session instrument may contribute when its range and units are appropriate. Add output-level contributors to the final budget when needed.",
      addBudget, { ...derived, revealedTarget: budgetMenu, hint: "Sensitivity coefficients translate input uncertainty into its effect on the output. The largest input uncertainty need not produce the largest output contribution." }),
    step("Derived measurement", "derived-correlation", "Account for correlated inputs",
      "Open Input correlation matrix when budget contributors share a known source of variation. Enter justified correlations and inspect the calculation breakdown. Close the correlation window when finished to continue to propagation settings. Correlation can increase or decrease the combined result compared with independent inputs.",
       '[aria-label="Input correlation matrix"]', { ...derived, revealedTarget: '.correlation-matrix-modal', dismissOnLeave: '[aria-label="Close input correlations"]', continueTarget: '.correlation-matrix-modal', prerequisite: "Select a derived point with at least two configured budget contributors to open the correlation matrix.", hint: "Use evidence for correlations. A shared instrument alone does not establish a numeric correlation coefficient." }),
    step("Derived measurement", "budget-method", "Choose uncertainty propagation",
      "Taylor Series uses local sensitivity coefficients. Enable Monte Carlo for sampled propagation through a derived equation and set the trial count. Recalculate when results are marked out of date and inspect nonlinearity or stationary-point warnings.",
      '.budget-propagation-control', { ...derived, hint: "Review method assumptions and the calculation breakdown before relying on the result." }),

    step("Budget controls & results", "budget-edit", "Review error sources",
      "Edit a manual source's name, error limit, distribution, and Type A/B classification in the budget. Use the row arrows to reorder and × to remove a contributor from this budget. Linked instrument sources use the underlying instrument specification.",
      '.budget-stack', { ...budget, hint: "An error limit is converted using its distribution. The Standard Uncertainty column shows the resulting standard value." }),
    step("Budget controls & results", "budget-dynamic", "Add a table or equation directly to a budget",
      "Use + and choose Add tabular component or Add equation component. The inline fields follow the instrument-table editors: set units, fill the table or formula, and choose distribution in its own column. Shared definitions can be reused from the picker.",
      addBudget, { ...budget, revealedTarget: budgetMenu, hint: "For equations, bind the appropriate variable to the measurement point. For tables, provide an entry matching the nominal." }),
    step("Budget controls & results", "repeatability", "Estimate repeatability from readings",
      "Choose Repeatability from + and enter repeated measurements in the appropriate unit. The app uses their sample standard deviation as standard uncertainty, with n − 1 degrees of freedom. Save the readings, then click Error Limit to reopen them.",
      addBudget, { ...budget, revealedTarget: '.repeatability-modal', hint: "Repeatability is Type A with fixed Normal (Std. Unc.) distribution. It uses the standard deviation of the readings, not the standard deviation of their mean." }),
    step("Budget controls & results", "budget-results", "Read the budget results",
      "Combined Uncertainty is the combined standard value. Expanded Uncertainty applies the coverage factor k at the chosen confidence. Effective DOF controls Welch–Satterthwaite handling of finite degrees of freedom. Hover results for more precision.",
      '.budget-results-card', { ...budget, hint: "A pending or undefined result needs attention. It is not equivalent to zero uncertainty." }),
    step("Budget controls & results", "budget-charts", "Inspect contributions and calculations",
      "The contribution graph is always shown beneath the final budget when results are available. Use it to identify the largest contributors, and, in a derived budget, open Calculation breakdown in the equation section to inspect the numbers and method.",
      '.budget-final-support', { ...budget, hint: "Improving a small contributor may have little effect on the combined uncertainty. Review dominant contributors first." }),
    step("Budget controls & results", "budget-warnings", "Resolve incomplete or incompatible inputs",
      "Inspect the point's Info icons and budget warnings. They identify missing values, incompatible units, uncovered ranges, missing table entries, or equation problems. Correct the underlying input and confirm the warning clears before using the result.",
      points, { ...budget, hint: "Not Set and an em dash indicate unavailable information; neither proves a passing measurement or zero risk." }),

    step("Risk & mitigation", "risk-inputs", "Understand the inputs driving risk",
      "Assumed REOP describes the estimated chance of remaining within tolerance at the current interval. PFA Required sets the false-acceptance target; REOP Required and the current calibration interval support interval recommendations. Confidence affects expanded uncertainty and TUR.",
      '[data-tour="session-requirements"]', { hint: "These are modeling inputs. Check them against your calibration program and the basis of the analysis." }),
    step("Risk & mitigation", "risk-columns", "Compare risk and mitigation",
      "Use Columns to add Risk, Mitigation (GB + Int), or Mitigation (Int Only) fields. PFA is false-acceptance probability; PFR is false-rejection probability. Click a supported metric for its breakdown and compare the current and mitigated results.",
      columns, { revealedTarget: '.sidebar-filter-dropdown', hint: "TUR compares tolerance span with expanded measurement uncertainty. A capability ratio alone does not describe all false-acceptance or false-rejection risk." }),
    step("Risk & mitigation", "risk-guardbands", "Compare guard bands and intervals",
      "GB Low and GB High are proposed acceptance limits; PFA + GB and PFR + GB show their modeled risks. Compare Cal Int + GB with Cal Int no GB and the corresponding targeted REOP values to see the two mitigation approaches.",
      points, { hint: "Tighter acceptance limits can reduce false acceptance while increasing false rejection. Review the assumptions and breakdown rather than treating a recommendation as a guarantee." }),
    step("Risk & mitigation", "point-requirements", "Override requirements for a specific point",
      "In Columns, add fields from Risk Inputs or Mitigation Inputs. Edit the actual point's cell to override the session default for that point. Clear the cell to return to the session default.",
      columns, { revealedTarget: '.sidebar-filter-dropdown', hint: "Point overrides do not change the session defaults. Use the Info indicators to review point-specific settings." }),
    step("Risk & mitigation", "risk-boundaries", "Recognize unavailable risk results",
      "Review the warnings when a metric is unavailable. Single-sided tolerances with an unknown measurement use the supported PFA-only case; other metrics can intentionally remain blank. Missing or incompatible budget inputs must be resolved before interpreting risk.",
      points, { hint: "Click a populated metric to inspect its calculation when a breakdown is available." }),

    step("Columns & workspace", "column-menu", "Choose and order point columns",
      "Open Columns. Displayed Columns on the left lists the current order: drag to reorder or use × to hide a field. Add Columns on the right has its own scrollbar. Clicking an available field adds it at the bottom; drag it to place it elsewhere.",
      columns, { revealedTarget: '.sidebar-filter-dropdown', hint: "Low/high limit pairs move together. The menu starts centered; drag its top bar to move it." }),
    step("Columns & workspace", "column-defaults", "Save your preferred column layout",
      "Use Set as Default to remember the displayed columns and their order in this browser. Reset Columns restores the saved defaults. The menu height follows Displayed Columns while the available-column list scrolls independently.",
      columns, { revealedTarget: '.sidebar-filter-dropdown', hint: "Section, UUT, and Value are editable data fields. Header labels remain centered regardless of the data alignment." }),
    step("Columns & workspace", "layout", "Make the workspace fit",
      "Drag the divider between Measurement Points and the instrument pane. Double-click it to cycle through fitting the point columns, a full-width point list, and fitting the instrument tables. Full-width points distribute the columns across the available width without a horizontal scrollbar.",
      '[aria-label="Resize measurement point list"]', { hint: "Press Enter on the focused divider to cycle views; Escape returns to a split view. The Value number, unit, and prefix stay together." }),
    step("Columns & workspace", "table-layout", "Adjust table height and zoom",
      "Drag an instrument table's bottom handle to set its height; double-click it to fit the rows again. Drag column dividers to resize. Ctrl/Cmd + mouse wheel zooms a table, and Ctrl/Cmd+0 resets layout sizes and zoom.",
      uut, { ...overview, hint: "Collapse measurement areas or sections you do not need. Expand All and Collapse All are in the Measurement Points header." }),

    step("Editing & shortcuts", "point-selection", "Select and edit points",
      "Click a field once to edit, including Section. Enter commits a Value edit and advances; Ctrl/Cmd+Enter inserts a point below. Escape cancels. Ctrl/Cmd-click toggles point selection; Shift-click selects a span. Right-click for available point and budget actions.",
      points, { hint: "Outside text fields, shortcuts act on the current selection. Inside a field, ordinary text editing still works." }),
    step("Editing & shortcuts", "clipboard", "Copy points and budgets",
      "Ctrl/Cmd+C copies selected points, Ctrl/Cmd+X cuts, and Ctrl/Cmd+V pastes into the selected destination. Ctrl/Cmd+B copies the single selected point's budget; use the destination's context menu to paste a budget. Ctrl/Cmd+Z undoes the last session change.",
      points, { hint: "After copying between areas, review UUT assignments, ranges, units, derived nominals, and budget contributors." }),

    step("Library, tools & session files", "library-sync", "Review library synchronization",
      "The Sync column shows an instrument's relationship to the shared library. Session edits can differ from the shared definition. Click Sync and review the confirmation before publishing local changes to the library.",
      tmde, { ...overview, hint: "Review shared-library updates deliberately; they are different from editing only the current analysis." }),
    step("Library, tools & session files", "instrument-builder", "Maintain reusable instruments",
      "Open Instrument builder to search and maintain reusable instrument definitions and ranges. Use Reverse traceability to inspect where an instrument is used before deciding how to change a shared definition.",
      '[aria-label="Instrument builder"]', { hint: "The session tables are the quickest place to edit the current analysis. The library tools help maintain definitions for reuse." }),
    step("Library, tools & session files", "unit-converter", "Check a unit conversion",
      "Open Unit converter from the header to check a conversion independently. When editing the analysis itself, choose units and prefixes in the field's own menus so the stored value and its meaning remain consistent.",
      '[aria-label="Unit converter"]'),
    step("Library, tools & session files", "notes", "Document the analysis",
      "Use Notes to record the method, assumptions, supporting images, and conclusions. Include why you chose the uncertainty sources, distributions, correlations, bias, and risk inputs so another user can review the analysis.",
      '[data-tour="tab-notes"]', { workspace: "notes", prerequisite: "Create or select a session to open Notes." }),
    step("Library, tools & session files", "session-files", "Export and restore a session",
      "Use Export session to PDF in the header to save the analysis, and Import session from PDF to load a previously exported session. Review warnings and the selected session before sharing. Reopen Help whenever you need a particular workflow.",
      '[aria-label="Import and export"]', { hint: "Import expects a session PDF exported by this app, not an arbitrary PDF report." }),
  ];
  // Teach the basic point/budget workflows before advanced source definitions.
  const advanced = steps.filter(step => step.workflow === "Additional uncertainties" || step.id === "budget-dynamic").map(step => ({ ...step, workflow: "Additional uncertainties" }));
  const basic = steps.filter(step => !advanced.some(item => item.id === step.id));
  const insertion = basic.findIndex(step => step.workflow === "Library, tools & session files");
  return [...basic.slice(0, insertion), ...advanced, ...basic.slice(insertion)];
};
