# Generated by Django 5.2.1 on 2026-06-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uncertainty', '0005_customequation'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='instrument',
            name='scope',
            field=models.CharField(choices=[('local', 'Local (user)'), ('validated', 'Validated (shared)')], default='validated', max_length=16),
        ),
        migrations.AddField(
            model_name='instrument',
            name='source_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='instrument',
            name='validated_snapshot',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
