# Generated by Django 5.2.1 on 2026-07-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uncertainty', '0007_measurementarea_hidden_from_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='function_groups',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
