# Generated by Django 5.2.4 on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uncertainty", "0011_manualcomponent_extra"),
    ]

    operations = [
        migrations.AddField(
            model_name="testpoint",
            name="equation_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
