import React, {useState} from 'react';
import { render, fireEvent, screen, within, waitFor } from '@testing-library/react';
import {it, expect, vi} from 'vitest';
import UncertaintyPanel from './UncertaintyPanel';
vi.mock('plotly.js-dist',()=>({default:{}}));
const makeItem=id=>({id,description:id,instrument:{functions:[{id:id+'f',name:'Current',unit:'A',ranges:[{id:id+'r',min:10,max:100,unit:'A',tolerances:{reading:{value:1,unit:'%'}}}]}]}});
function Harness({viewMode,grouped=false}) {
 const [session,save]=useState({id:'s',name:'Test',uuts:[grouped ? {...makeItem('u1'),instrument:{functions:[{id:'u1f',name:'Current',unit:'A',ranges:[0,1,2].map(index=>({id:`g${index}`,min:index*10,max:(index+1)*10,unit:'A',qualifierGroupId:`parent${index}`,qualifier:{id:`q${index}`,text:'Test',qualifier:{id:`nested${index}`,text:'Interval'}},tolerances:{reading:{value:index+1,unit:'%'}}}))}]}} : makeItem('u1'),makeItem('u2')],tmdes:[makeItem('t1')],testPoints:[],uncReq:{}});
 const point={id:'p',viewMode,testPointInfo:{parameter:{name:'Current',value:50,unit:'A'},qualifier:{value:200,unit:'Hz'}},associatedUutIds:['u1'],components:[],tmdeTolerances:[],specifications:{}};
 return <><UncertaintyPanel testPointData={point} sessionData={session} onSessionSave={save} uutNominal={point.testPointInfo.parameter} tmdeTolerancesData={[]} setNotification={()=>{}} onInstrumentSynced={()=>{}}/><output data-testid="state">{JSON.stringify(session)}</output></>;
}
it.each(['session','point'])('adds and merges qualifier sub-ranges in %s view',async viewMode=>{
 render(<Harness viewMode={viewMode}/>);
 let row=document.querySelector('tr[data-range-group="uut:u1"]');
 expect(within(row).queryByRole('button',{name:'Add qualifier',exact:true})).not.toBeInTheDocument();
 fireEvent.mouseDown(row.querySelector('[data-range-cell]'));
 fireEvent.click(within(row).getByRole('button',{name:'Add qualifier',exact:true}));
 row=document.querySelector('tr[data-range-group="uut:u1"]');
 const table=row.closest('table');
 expect(within(table).getByRole('button',{name:'Qualifier',exact:true})).toBeInTheDocument();
 expect(document.querySelector('tr[data-range-group="uut:u2"] [data-range-cell]')).toHaveAttribute('colspan','2');
 const qualifier=row.querySelector('[data-qualifier-cell]');
 expect(within(qualifier).getByRole('textbox',{name:'Qualifier value'})).toHaveFocus();
 const input=within(qualifier).getByRole('textbox',{name:'Qualifier value'});
 expect(within(qualifier).getAllByRole('textbox')).toHaveLength(1);
 fireEvent.change(input,{target:{value:'100 – 1000 Hz'}});
 fireEvent.blur(input);
 expect(JSON.parse(screen.getByTestId('state').textContent).uuts[0].instrument.functions[0].ranges[0].qualifier.text).toBe('100 – 1000 Hz');
 fireEvent.click(qualifier.querySelector('.inline-tolerance-summary'));
 fireEvent.keyDown(within(qualifier).getByRole('textbox',{name:'Qualifier value'}), {key:'Enter',ctrlKey:true});
 const rows=[...document.querySelectorAll('tr[data-range-group="uut:u1"]')];
 expect(rows).toHaveLength(2);
 expect(within(rows[1].querySelector('[data-qualifier-cell]')).getByRole('textbox',{name:'Qualifier value'})).toHaveFocus();
 expect(rows[0].querySelector('[data-range-cell]')).toHaveAttribute('rowspan','2');
 expect(rows[1].querySelectorAll('[data-range-cell]')).toHaveLength(1);
 fireEvent.mouseDown(rows[0].querySelector('[data-range-cell]'));
 expect(rows.every(r=>r.dataset.rangeSelected==='true')).toBe(true);
 fireEvent.mouseDown(rows[1].querySelector('[data-qualifier-cell]'));
 expect(rows[0].dataset.rangeSelected).toBe('false');
 expect(rows[1].dataset.rangeSelected).toBe('true');
 expect(table.dataset.selectionMode).toBe('instrument');
 fireEvent.pointerMove(rows[1].querySelector('[data-qualifier-cell]'));
 await waitFor(()=>expect(rows[0].querySelector('.cell-description')).toHaveAttribute('data-cell-selected'));
 expect(rows[0].querySelector('[data-range-cell]')).toHaveAttribute('data-cell-selected');
 const state=JSON.parse(screen.getByTestId('state').textContent);
 expect(state.uuts[0].instrument.functions[0].ranges).toHaveLength(2);
 fireEvent.click(within(rows[1]).getByRole('button',{name:'Delete qualifier range'}));
 expect(document.querySelectorAll('tr[data-range-group="uut:u1"]')).toHaveLength(1);
});

it.each(['session','point'])('nests text qualifiers and collapses parents in %s view', viewMode => {
 render(<Harness viewMode={viewMode}/>);
 let row=document.querySelector('tr[data-range-group="uut:u1"]');
 const base=row.querySelector('[data-range-cell]');
 fireEvent.mouseDown(base);
 fireEvent.click(base.querySelector('.inline-tolerance-summary'));
 fireEvent.click(within(row).getByRole('button',{name:'Add qualifier',exact:true}));
 expect(within(base).queryByPlaceholderText('min')).not.toBeInTheDocument();
 let first=row.querySelector('[data-qualifier-cell="1"]');
 fireEvent.change(within(first).getByRole('textbox',{name:'Qualifier value'}),{target:{value:'DC mode'}});
 fireEvent.blur(within(first).getByRole('textbox',{name:'Qualifier value'}));
 fireEvent.click(first.querySelector('.inline-tolerance-summary'));
 fireEvent.click(within(first).getByRole('button',{name:'Add nested qualifier'}));
 expect(within(first).queryByRole('textbox',{name:'Qualifier value'})).not.toBeInTheDocument();
 const child=row.querySelector('[data-qualifier-cell="2"]');
 expect(within(child).getByRole('textbox',{name:'Qualifier value'})).toHaveFocus();
 fireEvent.change(within(child).getByRole('textbox',{name:'Qualifier value'}),{target:{value:'90 days'}});
 fireEvent.blur(within(child).getByRole('textbox',{name:'Qualifier value'}));
 const table=row.closest('table');
 const header=table.querySelector('[data-instrument-column="qualifier2"]');
 fireEvent.click(within(header).getByRole('button',{name:'Qualifier',exact:true}));
 const name=within(header).getByRole('textbox',{name:'Qualifier 2 column name'});
 fireEvent.change(name,{target:{value:'Calibration interval'}});
 fireEvent.blur(name);
 expect(within(header).queryByRole('textbox')).toBeNull();
 expect(within(header).getByRole('button',{name:'Calibration interval'})).toHaveClass('instrument-custom-column-label');
 for(const area of table.querySelectorAll('.instrument-area-section-row > td')) expect(area.colSpan).toBe(table.tHead.rows[0].cells.length);

 fireEvent.click(within(child).getByRole('button',{name:'Add qualifier range',exact:true}));
 const rows=[...document.querySelectorAll('tr[data-range-group="uut:u1"]')];
 expect(rows).toHaveLength(2);
 expect(rows[0].querySelector('[data-qualifier-cell="1"]')).toHaveAttribute('rowspan','2');
 expect(rows[1].querySelector('[data-qualifier-cell="1"]')).toBeNull();
 const state=JSON.parse(screen.getByTestId('state').textContent);
 expect(state.qualifierColumnNames.uut[1]).toBe('Calibration interval');
 const ranges=state.uuts[0].instrument.functions[0].ranges;
 expect(ranges[0].qualifier.text).toBe('DC mode');
 expect(ranges[0].qualifier.qualifier.text).toBe('90 days');
 expect(ranges[1].tolerances).toEqual({});
});

it.each(['session','point'])('keeps custom columns as Name fields at their selected position beside nested qualifiers in %s',viewMode=>{
 render(<Harness viewMode={viewMode}/>);
 const row=document.querySelector('tr[data-range-group="uut:u1"]');
 fireEvent.mouseDown(row.querySelector('[data-range-cell]'));
 fireEvent.click(within(row).getByRole('button',{name:'Add qualifier',exact:true}));
 fireEvent.click(within(row).getByRole('button',{name:'Add nested qualifier'}));
 const table=row.closest('table');
 for(const [anchor,name] of [['range','Asset note'],['qualifier','Frequency note'],['qualifier2','Interval note']]) {
  const header=table.querySelector(`[data-instrument-column="${anchor}"]`);
  fireEvent.click(header.querySelector('.instrument-column-insert-button'));
  const input=within(table).getByRole('textbox',{name:'Column name',exact:true});
  expect(input).toHaveValue('Name');
  fireEvent.change(input,{target:{value:name}});fireEvent.blur(input);
  const headers=[...table.tHead.rows[0].cells];
  const index=headers.findIndex(cell=>within(cell).queryByRole('button',{name,exact:true}));
  expect(index).toBe(headers.indexOf(header)+1);
  expect(row.cells[index]).toHaveAttribute('data-custom-column',headers[index].dataset.instrumentColumn);
  expect(row.cells[index].querySelector('[placeholder="Qualifier"]')).toBeNull();
 }
 expect(row.querySelectorAll('[data-qualifier-cell]')).toHaveLength(2);
});

it.each(['session','point'])('uses existing shared-cell selection and highlighting for equal qualifiers in %s',async viewMode=>{
 render(<Harness viewMode={viewMode} grouped/>);
 const first=document.querySelector('tr[data-range-group="uut:u1"]');
 const expand=within(first).queryByRole('button',{name:'Edit ranges'});
 if(expand) fireEvent.click(expand);
 const rows=[...document.querySelectorAll('tr[data-range-group="uut:u1"]')];
 expect(rows).toHaveLength(3);
 const shared=rows[0].querySelector('[data-qualifier-cell="1"]');
 const nested=rows[0].querySelector('[data-qualifier-cell="2"]');
 expect(shared).toHaveAttribute('rowspan','3');expect(nested).toHaveAttribute('rowspan','3');
 expect(rows[1].querySelector('[data-qualifier-cell]')).toBeNull();
 expect(rows[2].querySelector('[data-qualifier-cell]')).toBeNull();
 expect(shared).not.toHaveAttribute('data-actions-selected');
 expect(nested).not.toHaveAttribute('data-actions-selected');
 fireEvent.mouseDown(shared);
 expect(shared).toHaveAttribute('data-actions-selected','true');
 expect(nested).toHaveAttribute('data-actions-selected','true');
 expect(rows.every(row=>row.dataset.rangeSelected==='true')).toBe(true);
 expect(first.closest('table').dataset.selectionMode).toBe('instrument');
 fireEvent.mouseDown(shared);
 expect(rows.every(row=>row.dataset.rangeSelected==='false')).toBe(true);
 expect(shared).not.toHaveAttribute('data-actions-selected');
 expect(nested).not.toHaveAttribute('data-actions-selected');
 fireEvent.mouseDown(rows[1].querySelector('.cell-tolerance'));
 fireEvent.pointerMove(rows[1].querySelector('.cell-tolerance'));
 await waitFor(()=>expect(shared).toHaveAttribute('data-cell-selected'));
 expect(nested).toHaveAttribute('data-cell-selected');
 expect(shared).toHaveAttribute('data-actions-selected','true');
 expect(nested).toHaveAttribute('data-actions-selected','true');
 fireEvent.click(shared.querySelector('.inline-tolerance-summary'));
 const input=within(shared).getByRole('textbox',{name:'Qualifier value'});
 fireEvent.change(input,{target:{value:'Updated'}});fireEvent.blur(input);
 const ranges=JSON.parse(screen.getByTestId('state').textContent).uuts[0].instrument.functions[0].ranges;
 expect(ranges.map(range=>range.qualifier.text)).toEqual(['Updated','Updated','Updated']);
 expect(ranges.map(range=>range.tolerances.reading.value)).toEqual([1,2,3]);
});
