import React, {useState} from 'react';
import { render, fireEvent, screen, within, waitFor } from '@testing-library/react';
import {it, expect, vi} from 'vitest';
import UncertaintyPanel from './UncertaintyPanel';
vi.mock('plotly.js-dist',()=>({default:{}}));
const makeItem=id=>({id,description:id,instrument:{functions:[{id:id+'f',name:'Current',unit:'A',ranges:[{id:id+'r',min:10,max:100,unit:'A',tolerances:{reading:{value:1,unit:'%'}}}]}]}});
function Harness({viewMode}) {
 const [session,save]=useState({id:'s',name:'Test',uuts:[makeItem('u1'),makeItem('u2')],tmdes:[makeItem('t1')],testPoints:[],uncReq:{}});
 const point={id:'p',viewMode,testPointInfo:{parameter:{name:'Current',value:50,unit:'A'},qualifier:{value:200,unit:'Hz'}},associatedUutIds:['u1'],components:[],tmdeTolerances:[],specifications:{}};
 return <><UncertaintyPanel testPointData={point} sessionData={session} onSessionSave={save} uutNominal={point.testPointInfo.parameter} tmdeTolerancesData={[]} setNotification={()=>{}} onInstrumentSynced={()=>{}}/><output data-testid="state">{JSON.stringify(session)}</output></>;
}
it.each(['session','point'])('adds and merges qualifier sub-ranges in %s view',async viewMode=>{
 render(<Harness viewMode={viewMode}/>);
 let row=document.querySelector('tr[data-range-group="uut:u1"]');
 expect(within(row).queryByRole('button',{name:'Add qualifier',exact:true})).not.toBeInTheDocument();
 fireEvent.mouseDown(row.querySelector('[data-range-cell]'));
 fireEvent.click(within(row).getByRole('button',{name:'Add qualifier',exact:true}));
 row=document.querySelector('tr[data-range-group="uut:u1"]');
 const table=row.closest('table');
 expect(within(table).getByRole('button',{name:'Qualifier',exact:true})).toBeInTheDocument();
 expect(document.querySelector('tr[data-range-group="uut:u2"] [data-range-cell]')).toHaveAttribute('colspan','2');
 const qualifier=row.querySelector('[data-qualifier-cell]');
 expect(within(qualifier).getByRole('textbox',{name:'Qualifier value'})).toHaveFocus();
 const input=within(qualifier).getByRole('textbox',{name:'Qualifier value'});
 expect(within(qualifier).getAllByRole('textbox')).toHaveLength(1);
 fireEvent.change(input,{target:{value:'100 – 1000 Hz'}});
 fireEvent.blur(input);
 expect(JSON.parse(screen.getByTestId('state').textContent).uuts[0].instrument.functions[0].ranges[0].qualifier.text).toBe('100 – 1000 Hz');
 fireEvent.click(qualifier.querySelector('.inline-tolerance-summary'));
 fireEvent.keyDown(within(qualifier).getByRole('textbox',{name:'Qualifier value'}), {key:'Enter',ctrlKey:true});
 const rows=[...document.querySelectorAll('tr[data-range-group="uut:u1"]')];
 expect(rows).toHaveLength(2);
 expect(within(rows[1].querySelector('[data-qualifier-cell]')).getByRole('textbox',{name:'Qualifier value'})).toHaveFocus();
 expect(rows[0].querySelector('[data-range-cell]')).toHaveAttribute('rowspan','2');
 expect(rows[1].querySelectorAll('[data-range-cell]')).toHaveLength(1);
 fireEvent.mouseDown(rows[0].querySelector('[data-range-cell]'));
 expect(rows.every(r=>r.dataset.rangeSelected==='true')).toBe(true);
 fireEvent.mouseDown(rows[1].querySelector('[data-qualifier-cell]'));
 expect(rows[0].dataset.rangeSelected).toBe('false');
 expect(rows[1].dataset.rangeSelected).toBe('true');
 fireEvent.mouseDown(rows[1].querySelector('.cell-tolerance'));
 fireEvent.pointerMove(rows[1].querySelector('.cell-tolerance'));
 await waitFor(()=>expect(rows[0].querySelector('.cell-description')).toHaveAttribute('data-cell-selected'));
 expect(rows[0].querySelector('[data-range-cell]')).toHaveAttribute('data-cell-selected');
 const state=JSON.parse(screen.getByTestId('state').textContent);
 expect(state.uuts[0].instrument.functions[0].ranges).toHaveLength(2);
 fireEvent.click(within(rows[1]).getByRole('button',{name:'Delete qualifier range'}));
 expect(document.querySelectorAll('tr[data-range-group="uut:u1"]')).toHaveLength(1);
});

it.each(['session','point'])('nests text qualifiers and collapses parents in %s view', viewMode => {
 render(<Harness viewMode={viewMode}/>);
 let row=document.querySelector('tr[data-range-group="uut:u1"]');
 const base=row.querySelector('[data-range-cell]');
 fireEvent.mouseDown(base);
 fireEvent.click(base.querySelector('.inline-tolerance-summary'));
 fireEvent.click(within(row).getByRole('button',{name:'Add qualifier',exact:true}));
 expect(within(base).queryByPlaceholderText('min')).not.toBeInTheDocument();
 let first=row.querySelector('[data-qualifier-cell="1"]');
 fireEvent.change(within(first).getByRole('textbox',{name:'Qualifier value'}),{target:{value:'DC mode'}});
 fireEvent.blur(within(first).getByRole('textbox',{name:'Qualifier value'}));
 fireEvent.click(first.querySelector('.inline-tolerance-summary'));
 fireEvent.click(within(first).getByRole('button',{name:'Add nested qualifier'}));
 expect(within(first).queryByRole('textbox',{name:'Qualifier value'})).not.toBeInTheDocument();
 const child=row.querySelector('[data-qualifier-cell="2"]');
 expect(within(child).getByRole('textbox',{name:'Qualifier value'})).toHaveFocus();
 fireEvent.change(within(child).getByRole('textbox',{name:'Qualifier value'}),{target:{value:'90 days'}});
 fireEvent.blur(within(child).getByRole('textbox',{name:'Qualifier value'}));
 const table=row.closest('table');
 const header=table.querySelector('[data-instrument-column="qualifier2"]');
 fireEvent.click(within(header).getByRole('button',{name:'Qualifier',exact:true}));
 const name=within(header).getByRole('textbox',{name:'Qualifier 2 column name'});
 fireEvent.change(name,{target:{value:'Calibration interval'}});
 fireEvent.blur(name);
 expect(within(header).queryByRole('textbox')).toBeNull();
 expect(within(header).getByRole('button',{name:'Calibration interval'})).toHaveClass('instrument-custom-column-label');
 for(const area of table.querySelectorAll('.instrument-area-section-row > td')) expect(area.colSpan).toBe(table.tHead.rows[0].cells.length);

 fireEvent.click(within(child).getByRole('button',{name:'Add qualifier range',exact:true}));
 const rows=[...document.querySelectorAll('tr[data-range-group="uut:u1"]')];
 expect(rows).toHaveLength(2);
 expect(rows[0].querySelector('[data-qualifier-cell="1"]')).toHaveAttribute('rowspan','2');
 expect(rows[1].querySelector('[data-qualifier-cell="1"]')).toBeNull();
 const state=JSON.parse(screen.getByTestId('state').textContent);
 expect(state.qualifierColumnNames.uut[1]).toBe('Calibration interval');
 const ranges=state.uuts[0].instrument.functions[0].ranges;
 expect(ranges[0].qualifier.text).toBe('DC mode');
 expect(ranges[0].qualifier.qualifier.text).toBe('90 days');
 expect(ranges[1].tolerances).toEqual({});
});
