import { expect, it } from 'vitest';
import vectors from './suppliedBiasParityVectors.json';
import { multiSourceCase } from '../../../../../scripts/multi-source-bias-cases.mjs';
import { computePointRiskMetrics, computeUncertaintyForPoint } from '../riskCompute';
import { resolveMeasurementBias } from '../measurementBias';

// Three-way check: two signed TMDE percentages, an equivalent manual net, and
// cached Excel values. Expected risk is never generated by the implementation.
for (const derived of [false, true]) it.each(vectors.cases.filter(v => v.type <= 4))(`two sources / net / Excel (${derived ? 'derived' : 'direct'}) row $row`, vector => {
  const { point, session } = multiSourceCase(vector, derived);
  const before = computeUncertaintyForPoint(point, session);
  expect(resolveMeasurementBias(point, session).calBias).toBeCloseTo(vector.calBias * 10, 12);
  const sources = computePointRiskMetrics(point, session, true);
  const net = { ...point, measurementBias: { mode: 'manual', kind: 'percent', value: vector.calBias * 100, unit: 'V' } };
  expect(computeUncertaintyForPoint(net, session)).toEqual(before);
  expect(computePointRiskMetrics(net, session, true)).toEqual(sources);
  for (const [key, expected] of Object.entries(vector.expected)) {
    // Two independent specification bounds have a wider worst-case sum even
    // though their RSS uncertainty is identical. Verify that difference too.
    const oracle = key === 'tar' ? expected / Math.sqrt(2) : expected;
    expect(Math.abs(sources[key] - oracle), key).toBeLessThanOrEqual(1e-8 + Math.abs(oracle) * 1e-8);
  }
});
