# Generated by Django 6.1 on 2026-09-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('default_nomenclature', models.CharField(blank=True, default='', max_length=255)),
                ('submitted_label', models.CharField(blank=True, default='Submitted by:', max_length=255)),
                ('statements', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ROCRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roc_number', models.CharField(blank=True, default='', max_length=64)),
                ('nomenclature', models.CharField(blank=True, default='', max_length=255)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=255)),
                ('model_number', models.CharField(blank=True, default='', max_length=255)),
                ('serial_number', models.CharField(blank=True, default='', max_length=255)),
                ('procedure_used', models.CharField(blank=True, default='', max_length=255)),
                ('submitted_label', models.CharField(blank=True, default='Submitted by:', max_length=255)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_address', models.CharField(blank=True, default='', max_length=255)),
                ('area_code', models.CharField(blank=True, default='', max_length=32)),
                ('area_name', models.CharField(blank=True, default='', max_length=255)),
                ('statements', models.JSONField(blank=True, default=list)),
                ('ambient_temperature', models.CharField(blank=True, default='', max_length=32)),
                ('relative_humidity', models.CharField(blank=True, default='', max_length=32)),
                ('calibration_date', models.CharField(blank=True, default='', max_length=32)),
                ('due_date', models.CharField(blank=True, default='', max_length=32)),
                ('issue_date', models.CharField(blank=True, default='', max_length=32)),
                ('metrologist_name', models.CharField(blank=True, default='', max_length=255)),
                ('metrologist_title', models.CharField(blank=True, default='', max_length=255)),
                ('approver_name', models.CharField(blank=True, default='', max_length=255)),
                ('approver_title', models.CharField(blank=True, default='', max_length=255)),
                ('inline_results', models.JSONField(blank=True, default=list)),
                ('tables', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
