# Generated by Django 4.2.7 on 2026-09-03 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeasurementArea',
        ),
    ]
