# Generated by Django 6.1.1 on 2026-09-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_delete_measurementarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(blank=True, default='', max_length=255)),
                ('sub_custodian', models.CharField(blank=True, default='', max_length=255)),
                ('lab_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('syscom', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['lab_name', 'activity', 'sub_custodian', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
