# Generated by Django 6.1.1 on 2026-09-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_testpoint_correction_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationsettings',
            name='settling_time',
            field=models.FloatField(blank=True, default=120, null=True),
        ),
    ]
