# Generated by Django 6.1.1 on 2026-09-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_calibrationsettings_settling_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationresults',
            name='outlier_filter_mode',
            field=models.CharField(choices=[('none', 'None'), ('auto', 'Auto (Chauvenet/IQR)')], default='auto', help_text='Outlier auto-rejection mode applied during pair aggregation. Mirrored across the pair.', max_length=16),
        ),
    ]
